/*
 * Copyright 2013 Andrew Everitt, Andrew Heckford, Daniele Masato
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.raje.maven.plugin.msbuild;

import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.codehaus.plexus.util.cli.StreamConsumer;

import uk.org.raje.maven.plugin.msbuild.configuration.BuildConfiguration;
import uk.org.raje.maven.plugin.msbuild.configuration.BuildPlatform;
import uk.org.raje.maven.plugin.msbuild.configuration.CxxTestConfiguration;

/**
 *  
 */
@Mojo( name = CxxTestRunnerMojo.MOJO_NAME, defaultPhase = LifecyclePhase.TEST )
public class CxxTestRunnerMojo extends AbstractMSBuildMojo
{
    /**
     * The name this Mojo declares, also represents the goal.
     */
    public static final String MOJO_NAME = "test";

    @Override
    public void doExecute() throws MojoExecutionException, MojoFailureException
    {
        if ( !isCxxTestEnabled( "runner execution" ) )
        {
            return;
        }
        
        validateCxxTestConfiguration();

        for ( String testTarget : cxxTest.testTargets() ) 
        {
            for ( BuildPlatform platform : platforms ) 
            {
                for ( BuildConfiguration configuration : platform.getConfigurations() )
                {
                    getLog().info( "Running " + CxxTestConfiguration.CXXTEST_NAME + " tests for target " + testTarget 
                            + ", platform=" + platform.getName() + ", configuration=" + configuration.getName() );

                    try 
                    {
                        executeCxxTestTarget( testTarget, platform, configuration );
                    }
                    catch ( MojoExecutionException mee )
                    {
                        getLog().error( mee.getMessage() );
                        throw mee;
                    }
                    catch ( MojoFailureException mfe )
                    {
                        getLog().error( mfe.getMessage() );
                        throw mfe;
                    }
                }
            }
        }

        getLog().info( "All tests passed." );
    }
    
    private void executeCxxTestTarget( String testTarget, BuildPlatform platform, BuildConfiguration configuration )
        throws MojoExecutionException, MojoFailureException
    {
        int exitCode = 0;
        
        File workingDirectory = MojoHelper.getConfigurationOutputDirectory( projectFile.getParentFile(), 
                platform, configuration, getLog() );
        
        File testTargetExec = new File( workingDirectory, new File ( testTarget ).getName() + ".exe" );
        
        CxxTestRunner cxxTestRunner = new CxxTestRunner( testTargetExec, 
                new MojoHelper.LogOutputStreamConsumer( getLog() ), new MojoHelper.ErrStreamConsumer( getLog() ) );
        
        cxxTestRunner.setWorkingDirectory( workingDirectory );

        try
        {
            exitCode = cxxTestRunner.runCommandLine();
        }
        catch ( IOException ioe )
        {
            throw new MojoExecutionException( "I/O error while executing test command line", ioe );
        }
        catch ( InterruptedException ie )
        {
            throw new MojoExecutionException( "Process interrupted while test executing command line", ie );
        }
        
        if ( exitCode != 0 )
        {
            throw new MojoFailureException( "Some tests failed to pass." );
        }
    }
    
    /**
     * Runs a given test target (executable generated by a Visual C++ test project) and produces a test report.
     */
    private class CxxTestRunner extends CommandLineRunner
    {
        public CxxTestRunner( File testTargetExec, StreamConsumer outputConsumer, StreamConsumer errorConsumer )
        {
            super( outputConsumer, errorConsumer );
            this.testTargetExec = testTargetExec;
        }
        
        @Override
        protected List<String> getCommandLineArguments() 
        {
            List<String> commandLineArguments = new LinkedList<String>();
            commandLineArguments.add( testTargetExec.getAbsolutePath() );

            return commandLineArguments;
        }
        
        private File testTargetExec;
    }
    
}
